# Main params
NUM_CLASSES: 5
BATCH_SIZE: 75
K_NEIGHBORS: 3
USE_BIAS: True
#TODO remote config overwrite from main cfg (low priority)
#Model skeleton
TOPOLOGY: [ 'BACKBONE_2D', 'DT' ] # listing here includes module (BACKBONE & KNN are enforced)

BACKBONE_2D:
  NAME: DN7_CNN2d # DN4_CNN2d |DN7_CNN2d |ResNet2d
  MODE: TRAIN
  NORM: batch
  CUDA: True
  LEARNING_RATE: 0.005
  BETA_ONE: [ 0.5,0.9 ]
  INIT_WEIGHTS: kaiming

ENCODER:
  NAME: DefaultDual
  MODE: TRAIN
  NORM: batch
  CUDA: True
  FLATTENED_INPUT: 40000
  INPUT_SIZE: 64
  SMAX_LR: 0.1
  RED_LR: 0.005
  BETA_ONE: [ 0.5,0.9 ]
  INIT_WEIGHTS: kaiming

DT:
  NAME: XGB # XGB | RF
  MODE: TRAIN
  CUDA: True
  PARAMETERS: { } # add parameters here to override default settings


AUGMENTOR:
  TRANSFORMS: [
    {
      NAME: Resize,
      ARGS: [ [ 100,100 ] ],
      ENABLE: True,
    },
    { NAME: RandomCrop,
      ARGS: [ 48 ],
      ENABLE: False
    },
    { NAME: ColorJitter,
      ARGS: { brightness: 0.4, contrast: 0.4, saturation: 0.4 },
      ENABLE: False
    },
    { NAME: RandomHorizontalFlip,
      ARGS: [ ],
      ENABLE: False
    }
  ]


#BACKBONE & ENCODER

#Decision Tree
DATASET:


# Dataloader
DATASET_DIR: '../dataset/miniImageNet/'
DATA_NAME: 'miniImageNet'
OUTF: '../results/DN7'
BASEMODEL: 'Conv64F'
WORKERS: 8
IMAGE_SIZE: 84
EPISODE_SIZE: 1
TEST_EPISODE_SIZE: 1
EPOCHS: 30
EPISODE_TRAIN_NUM: 8000
EPISODE_VAL_NUM: 600
EPISODE_TEST_NUM: 600
WAY_NUM: 5
SHOT_NUM: 5
QUERY_NUM: 15

# Misc
PRINT_FREQ: 100